import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { NavbarVisibility } from "@/components/navbar-visibility";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="w-full">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
			>
				<NavbarVisibility>
					<Navbar />
				</NavbarVisibility>
				<main className="flex flex-col min-h-screen w-full bg-neutral-100 dark:bg-gray-900">
					{children}
				</main>
			</body>
		</html>
	);
}
